### ISSUE TITLE
Link warning on compilation

### ISSUE THREAD

**Issue by gtuna** [S-100ExpertTeam/khoa-lib-s100fc#1]
DLL_MessageProcess.vcxproj does not link on compilation 

the warning mesage is:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1967,5): warning : The referenced project '..\DLL_MessageProcess\DLL_MessageProcess.vcxproj' does not exist.`

![screenshot](https://user-images.githubusercontent.com/16979311/150525139-39ed484b-df4f-44f2-a81d-51459c7e4ad6.jpg)

**Comment by dnwkfkwk** [comment]
> DLL_MessageProcess.vcxproj does not link on compilation
> 
> the warning mesage is:
> 
> `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1967,5): warning : The referenced project '..\DLL_MessageProcess\DLL_MessageProcess.vcxproj' does not exist.`
> 
> ![screenshot](https://user-images.githubusercontent.com/16979311/150525139-39ed484b-df4f-44f2-a81d-51459c7e4ad6.jpg)

It is not used in this project now. 
So, will delete from this project shortly.
